"use client";

import { useSearchParams } from 'next/navigation';
import { useEffect, useState, Suspense } from 'react';
import styles from './invoice.module.css';

interface InvoiceData {
    s: string; // Shop Name
    a?: string; // Address
    p?: string; // Phone
    g?: string; // GSTIN
    d: string; // Date
    i: Array<{
        n: string; // Name
        q: number; // Qty
        u: string; // Unit
        p: number; // Price
    }>;
    t: number; // Total
}

function InvoiceContent() {
    const searchParams = useSearchParams();
    const dataParam = searchParams.get('data');
    const [invoice, setInvoice] = useState<InvoiceData | null>(null);
    const [error, setError] = useState("");

    useEffect(() => {
        if (dataParam) {
            try {
                // Determine format (Base64 vs Raw)
                // For URL safety, we expect Base64 encoded JSON
                const json = atob(dataParam);
                const data = JSON.parse(json);
                setInvoice(data);
            } catch (e) {
                console.error("Failed to parse invoice data", e);
                setError("Invalid Invoice Link");
            }
        } else {
            setError("No Invoice Data Found");
        }
    }, [dataParam]);

    if (error) {
        return <div className={styles.error}>{error}</div>;
    }

    if (!invoice) {
        return <div className="p-10 text-center text-gray-500">Loading Invoice...</div>;
    }

    const subTotal = invoice.t / 1.18; // Assuming 18% GST was included
    const gst = invoice.t - subTotal;

    return (
        <div className={styles.container}>
            <div className={styles.invoice}>
                <div className={styles.header}>
                    <h1 className={styles.shopName}>{invoice.s || "Store"}</h1>
                    <div className={styles.meta}>
                        {invoice.a && <p>{invoice.a}</p>}
                        {invoice.p && <p>Phone: {invoice.p}</p>}
                        {invoice.g && <p>GSTIN: {invoice.g}</p>}
                        <p style={{ marginTop: '10px' }}>Date: {new Date(invoice.d).toLocaleString()}</p>
                    </div>
                </div>

                <table className={styles.itemsTable}>
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th style={{ textAlign: 'center' }}>Qty</th>
                            <th style={{ textAlign: 'right' }}>Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {invoice.i.map((item, idx) => (
                            <tr key={idx}>
                                <td>{item.n}</td>
                                <td style={{ textAlign: 'center' }}>{item.q} {item.u}</td>
                                <td style={{ textAlign: 'right' }}>₹{(item.p * item.q).toFixed(2)}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>

                <div className={styles.totalSection}>
                    {/* Re-calculate totals roughly if strict subtotal isn't passed */}
                    <div className={styles.row}>
                        <span>Subtotal</span>
                        <span>₹{subTotal.toFixed(2)}</span>
                    </div>
                    <div className={styles.row}>
                        <span>Tax (18%)</span>
                        <span>₹{gst.toFixed(2)}</span>
                    </div>
                    <div className={styles.totalRow}>
                        <span>Grand Total</span>
                        <span>₹{invoice.t.toFixed(2)}</span>
                    </div>
                </div>

                <div className={styles.footer}>
                    <p>Thank you for your business!</p>
                    <p>Digital Receipt generated by TrackEezy</p>
                </div>
            </div>
        </div>
    );
}

export default function InvoicePage() {
    return (
        <Suspense fallback={<div>Loading...</div>}>
            <InvoiceContent />
        </Suspense>
    );
}
