import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import styles from './InvoicePage.module.css';

export default function InvoicePage() {
    const [searchParams] = useSearchParams();
    const dataParam = searchParams.get('data');
    const [invoice, setInvoice] = useState(null);
    const [error, setError] = useState("");

    useEffect(() => {
        if (dataParam) {
            try {
                // Decode Base64 JSON
                const json = atob(dataParam);
                const data = JSON.parse(json);
                setInvoice(data);
            } catch (e) {
                console.error("Failed to parse invoice data", e);
                setError("Invalid Invoice Link");
            }
        } else {
            setError("No Invoice Data Found");
        }
    }, [dataParam]);

    if (error) {
        return <div className={styles.error}>{error}</div>;
    }

    if (!invoice) {
        return <div className="p-10 text-center text-gray-500">Loading Invoice...</div>;
    }

    // Calculations
    const total = parseFloat(invoice.t) || 0;
    const subTotal = total / 1.18; // Reverse calc assuming 18% GST was included in Total
    const gst = total - subTotal;

    return (
        <div className={styles.container}>
            <div className={styles.invoice}>
                <div className={styles.header}>
                    <h1 className={styles.shopName}>{invoice.s || "Store"}</h1>
                    <div className={styles.meta}>
                        {invoice.a && <p>{invoice.a}</p>}
                        {invoice.p && <p>Phone: {invoice.p}</p>}
                        {invoice.g && <p>GSTIN: {invoice.g}</p>}
                        <p style={{ marginTop: '10px' }}>Date: {new Date(invoice.d).toLocaleString()}</p>
                    </div>
                </div>

                <table className={styles.itemsTable}>
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th style={{ textAlign: 'center' }}>Qty</th>
                            <th style={{ textAlign: 'right' }}>Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {invoice.i.map((item, idx) => (
                            <tr key={idx}>
                                <td>{item.n}</td>
                                <td style={{ textAlign: 'center' }}>{item.q} {item.u}</td>
                                <td style={{ textAlign: 'right' }}>₹{(item.p * item.q).toFixed(2)}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>

                <div className={styles.totalSection}>
                    <div className={styles.row}>
                        <span>Subtotal</span>
                        <span>₹{subTotal.toFixed(2)}</span>
                    </div>
                    <div className={styles.row}>
                        <span>Tax (18%)</span>
                        <span>₹{gst.toFixed(2)}</span>
                    </div>
                    <div className={styles.totalRow}>
                        <span>Grand Total</span>
                        <span>₹{total.toFixed(2)}</span>
                    </div>
                </div>

                <div className={styles.footer}>
                    <p>Thank you for shopping!</p>
                    <p>Digital Receipt generated by BijNex</p>
                </div>
            </div>
        </div>
    );
}
